SELECT * FROM ARTICULOS;

INSERT INTO ARTICULOS VALUES(2,'VAPORESSO REVENGER X', 2, 2, 3800, 'JSDANFSAHFISDFOSDYFNSDOUFYF');

UPDATE ARTICULOS
SET habilitado = 1
where id_articulo >= 0;

SELECT * FROM MARCA;

INSERT INTO MARCA VALUES(2,'VAPORESSO');

SELECT * FROM CATEGORIA;

INSERT INTO CATEGORIA VALUES(2,'MODS');


ALTER TABLE ARTICULOS
ADD habilitado int;