SELECT * FROM ARTICULOS;

INSERT INTO ARTICULOS VALUES(2,'VAPORESSO REVENGER X', 2, 2, 3800, 'JSDANFSAHFISDFOSDYFNSDOUFYF');
INSERT INTO ARTICULOS VALUES(3,'SMOK T-PRIV 220W', 1, 2, 4500, 'SFANDSDYNFUYSDFIDSHFSDIF',1);

UPDATE ARTICULOS
SET habilitado = 1
where id_articulo >= 0;

SELECT * FROM MARCA;

INSERT INTO MARCA VALUES(2,'VAPORESSO');

SELECT * FROM CATEGORIA;

INSERT INTO CATEGORIA VALUES(2,'MODS');


ALTER TABLE ARTICULOS
ADD habilitado int;

ALTER TABLE ARTICULOS
ADD imgname VARCHAR(50);

UPDATE ARTICULOS
SET imgname = 1
where id_articulo = 1;


SELECT categoria.NOMBRE_CATEGORIA , articulos.id_categoria
FROM articulos
INNER JOIN categoria WHERE CATEGORIA.id_categoria = ARTICULOS.id_categoria;